#!/usr/bin/env bash

svg=./svgr_raw/logo.svg

size=(16 24 32 64)
out=""
for i in ${size[@]}; do
  inkscape --export-filename="./icon-$i.png" $svg -w $i -h $i 
  out+="icon-$i.png "
done

size=(192 512)
for i in ${size[@]}; do
  inkscape --export-filename="./icon-$i.png" $svg -w $i -h $i 
done

convert $out favicon.ico

mv favicon.ico icon-192.png icon-512.png ../static
